### PR TITLE
Changing credits on license

### PR DESCRIPTION
**Pull request by geovanisouza92**
- [x] I ran `npm test` for the package I'm modifying
- [x] I used `npm run commit` instead of `git commit`
- [x] I have rebased my branch onto master before merging

### CODE REVIEW

**Comment by Widdershin** [comment]
Hmmm, can a community copyright some code? I love the idea, just worried that it might make the license invalid.

**Comment by geovanisouza92** [comment]
@Widdershin To me, it seems to selfish take all the credits, when clearly there are more people contributing, at least with a issue or question.

I'm not sure about the validity of the license for a community. Do you have another idea?

**Comment by nickbalestra** [comment]
@geovanisouza92 @Widdershin what do we want to do with this? 

I personally think we could add a contributors.md instead as I've seen elsewhere (i.e on standard where they even have a nice script to auto generate it that we could perhaps borrow - https://github.com/feross/standard/blob/master/bin/update-authors.sh). 
This will leave the licence as it is so that we are sure it's valid. If you ok with this I'll go ahead close this PR and open an issue to move ahead with the contributors.md idea.

**Comment by Widdershin** [comment]
I think that's the best move. I asked around and it seems like without a
formal legal entity representing the community it's best for us to stick
with the creator in the LICENSE file.

I really like the idea of a contributors file! Go for it.

**Pull request closed without merging**
