### PR TITLE
docs(META): Fixed links repo urls

### PR DESCRIPTION
**Pull request by nickbalestra**
- [x] I ran `npm test` for the package I'm modifying
- [x] I used `npm run commit` instead of `git commit`

ISSUES CLOSED: #20

@geovanisouza92 I thought it was a good time to uniform the various url reference pointing inside this repo. 
Feel free to close this if you think is better to keep them like they are atm.

### CODE REVIEW

**Comment by nickbalestra** [comment]
I was wondering if [those link](https://github.com/cyclejs-community/create-cycle-app/blob/master/cycle-scripts-es-webpack/package.json#L17) should actually point to the monorepo or to the relative package path.

 I guess npm will use those to pull the relative readme&co and it I think it would be preferred to have the specific readmes published there instead of the generic one relative to the monorepo. Thinking loud here as I don't have enough experience with monorepos, so i still need to investigate this.

Im sure @TylorS knows better and perhaps can shed some light  on this

**Comment by TylorS** [comment]
What's the question I'm being asked here?

**Comment by nickbalestra** [comment]
@TylorS should the links in the package.json of a sub package (like [this](https://github.com/cyclejs-community/create-cycle-app/blob/master/create-cycle-app/package.json#L25)) point to the parent (the monorepo) or to the subpacke itself. I would say the latest for publishing reasons (npm readmes being pulled,...). but not too sure.

**Comment by TylorS** [comment]
I'd leave it to the parent repository URL. NPM is actually intelligent enough to upload READMEs of the local package when published.

**Pull request merged**
