### PR TITLE
feat(cycle-scripts-es-webpack): Added flavor for ES6 + Webpack

### PR DESCRIPTION
**Pull request by nickbalestra**
@geovanisouza92  I've added the first of the two webpack based flavors that we want to ship with the create-cycle-app.

I wasn't sure how to proceede with creating the Changelog.md that I saw you had on the other 2 flavors (It seems that running `release` checks on master for the previous package.json version... any directions will be appreciated)

### CODE REVIEW

**Comment by geovanisouza92** [comment]
Ok Nick, I really appreciate your work here, thank you again! :smile: 

I just pushed a change to the test script on root package.json about standard styleguide checking, but I see that you already addressed the offenses, so, just double check to see if not was missed.

About the release, I just added an PR template to the repo remembering to use `npm run commit` instead `git commit`. It uses comittizen behind the scenes, to ensure we use standard commit messages, that conventional-changelog could use later to create/update the CHANGELOG.md files. Thanks to @TylorS and northbrook (he's working to enhance even more the tool).

I have tested the flavor, it works really nice, except the `test.js` that throws an error about missing mocha bin and so on... I think it's really important to make these basic scripts work well for users, so, can you try to fix it?

**Comment by nickbalestra** [comment]
Sure Geovani, thanks for the review!
Im on it.

**Comment by nickbalestra** [comment]
@geovanisouza92 done, tests should now run fine. Btw, northbrook is awesome!!
(Mocha was searching through the node_modules)

**Comment by TylorS** [comment]
Just chiming in on this, really great to see new community contribution and activity :)

Also, please open issues on Northbrook if you run into anything. I'm neck deep in a rewrite to make it more intuitive and testable for plugin authors and very open and available for changes in course where it makes sense :)

**Pull request merged**
