### PR TITLE
fix(cycle-scripts-es-browserify): Fix babel transpilation by adding .babelrc

### PR DESCRIPTION
**Pull request by Widdershin**

### CODE REVIEW

**Comment by geovanisouza92** [comment]
@Widdershin What is this about?

**Comment by Widdershin** [comment]
babel only seems to work if I create a `.babelrc` file, which is what I'm used to. For example, using `import` will not work unless you add this `.babelrc` file.

**Comment by geovanisouza92** [comment]
Have you see that this option is [already included on the build script](https://github.com/cyclejs-community/create-cycle-app/blob/master/cycle-scripts-es-browserify/scripts/build.js#L24)?

**Comment by Widdershin** [comment]
I hadn't seen that, I was running into this running `npm test`.

**Comment by geovanisouza92** [comment]
I have tested manually each flavor, with each stream lib to ensure that it works seamlessly until #3 be resolved.

**Comment by Widdershin** [comment]
It works off the bat, but if you say, use an `import` in a test file, it will break.

**Comment by geovanisouza92** [comment]
Ok, it seems a bug then.

**Pull request closed without merging**
